In [61]:
import numpy as np
import math
np.set_printoptions(suppress=True)

In [62]:
macierz_T = np.array([
    [1,1,1,1,1,1,1,1],
    [1,1,1,1,-1,-1,-1,-1],
    [1,1,-1,-1,0,0,0,0],
    [0,0,0,0,1,1,-1,-1],
    [1,-1,0,0,0,0,0,0],
    [0,0,1,-1,0,0,0,0],
    [0,0,0,0,1,-1,0,0],
    [0,0,0,0,0,0,1,-1],
])

In [63]:
macierz = np.transpose(macierz_T)
macierz

array([[ 1,  1,  1,  0,  1,  0,  0,  0],
       [ 1,  1,  1,  0, -1,  0,  0,  0],
       [ 1,  1, -1,  0,  0,  1,  0,  0],
       [ 1,  1, -1,  0,  0, -1,  0,  0],
       [ 1, -1,  0,  1,  0,  0,  1,  0],
       [ 1, -1,  0,  1,  0,  0, -1,  0],
       [ 1, -1,  0, -1,  0,  0,  0,  1],
       [ 1, -1,  0, -1,  0,  0,  0, -1]])

In [64]:
macierz_T @ macierz

array([[8, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 2]])

#### jeżeli macierz transponowana @ macierz = diagonalana to znaczy, że wektory są ortagonalne ( prostopadłe)

In [67]:
# dlugosc = pierwiestek iloczyny skalarnego wkeotra przez siebie


macierz_jed = []
for wektor in np.transpose(macierz):
    dl = math.sqrt(np.dot(wektor, wektor))
    print(dl)
    wektor = wektor / dl
    macierz_jed.append(wektor)

macierz_jed = np.array(np.transpose(macierz_jed))
macierz_jed

2.8284271247461903
2.8284271247461903
2.0
2.0
1.4142135623730951
1.4142135623730951
1.4142135623730951
1.4142135623730951


array([[ 0.35355339,  0.35355339,  0.5       ,  0.        ,  0.70710678,
         0.        ,  0.        ,  0.        ],
       [ 0.35355339,  0.35355339,  0.5       ,  0.        , -0.70710678,
         0.        ,  0.        ,  0.        ],
       [ 0.35355339,  0.35355339, -0.5       ,  0.        ,  0.        ,
         0.70710678,  0.        ,  0.        ],
       [ 0.35355339,  0.35355339, -0.5       ,  0.        ,  0.        ,
        -0.70710678,  0.        ,  0.        ],
       [ 0.35355339, -0.35355339,  0.        ,  0.5       ,  0.        ,
         0.        ,  0.70710678,  0.        ],
       [ 0.35355339, -0.35355339,  0.        ,  0.5       ,  0.        ,
         0.        , -0.70710678,  0.        ],
       [ 0.35355339, -0.35355339,  0.        , -0.5       ,  0.        ,
         0.        ,  0.        ,  0.70710678],
       [ 0.35355339, -0.35355339,  0.        , -0.5       ,  0.        ,
         0.        ,  0.        , -0.70710678]])

In [71]:

np.round(np.transpose(macierz_jed) @ macierz_jed, decimals=1)

array([[ 1., -0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [77]:
x = np.array([8, 6 ,2 ,3 ,4 ,6, 6, 5])
x

array([8, 6, 2, 3, 4, 6, 6, 5])

In [80]:
x_new = np.transpose(macierz_jed) @ x
x_new

array([14.14213562, -0.70710678,  4.5       , -0.5       ,  1.41421356,
       -0.70710678, -1.41421356,  0.70710678])